import os, sys, argparse

def post_process_ts(file_name):
	"""
	Post process ts.txt files generated by parse.py.
	We need to do this to adjust some time skews introduced in CamFlow.
	"""
	current = 0.0
	out = open(file_name.split('.')[0] + '-post.txt', 'w+')
	with open(file_name) as f:
		for line in f:
			ts = float(line.strip())
			if ts > current:
				current = ts
			out.write(str(current) + '\n')
	f.close()
	out.close()

if __name__ == "__main__":
	parser = argparse.ArgumentParser(description='Post process timestamp files generated by parse.py.')
	parser.add_argument('-i', '--input', help='input data file path', required=True)
	args = parser.parse_args()

	post_process_ts(args.input)

